version: "2"

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - "./public_html:/var/www/public"
      - "./frontend:/var/www/frontend"
      - "./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php

  php:
    image: php:7.3-fpm
    build:
      context: "."
      dockerfile: "./etc/php/Dockerfile"
    working_dir: "/var/www"
    volumes:
    - ".:/var/www"
    - "./public_html:/var/www/public"
    - "./etc/php/log-stdout.conf:/usr/local/etc/php-fpm.d/zz-log.conf"
    - "./etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    - "./etc/php/options.ini:/usr/local/etc/php/conf.d/options.ini"
    environment:
      - XDEBUG_CONFIG=remote_host=${HOST_IP}
      - MONGO_HOST=mongo
      - MONGO_DB=amoauto
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - "./etc/database/mongo:/data/db"
    ports:
      - 27317:27017